- symbols/arm9.yml
- symbols/literals.yml
- symbols/overlay10.yml
- symbols/ram.yml
This adds WONDER_GUMMI_IQ_GAIN and SCRIPT_VARS_VALUES and fixes some missing length values for EU.
> Three additions and two fixes for missing EU values

- symbols/arm9.yml
- symbols/overlay11.yml
From the old pmd2data.xml file
> Add JP symbols from skytemple-files

- headers/types/common/common.h
This one totally went past me! I'll correct it now that I've realized before I forget haha
> Correct WTE format field name

- headers/functions/arm9.h
- headers/functions/overlay29.h
- symbols/arm9.yml
- symbols/overlay29.yml
This one took way more tries than I'd like to admit to get right, but here it is n-n
> Symbols for changing window palettes

- symbols/arm9.yml
- symbols/overlay11.yml
- symbols/overlay29.yml
These addresses were all located automatically by the script.
> Add EU function addresses found by symbols_vfill.py

- CREDITS.txt
- headers/types/ground_mode/ground_mode.h
- symbols/overlay11.yml
That's a pretty simple change, to test a bit the CI (but entered information are valid, at least AFAIK)
> add the main_ground_data pointer

- .github/workflows/check-function-sync.yml
- .github/workflows/check-symbols.yml
- .github/workflows/release.yml
- headers/symbol_check.py
- symbols/README.md
- tools/symbols_vfill.py
Closes #56.
Subregion support was added to resymgen with https://github.com/UsernameFodder/pmdsky-debug/issues/37. The rest of pmdsky-debug should also be updated to support subregions, in preparation for future subregions.
> Support subregions in pmdsky-debug

- headers/functions/arm9.h
- headers/types/common/common.h
- headers/types/common/file_io.h
- symbols/arm9.yml
I happened to be looking for stuff related to how the weather is displayed in the Overworld, but got sidetracked by this nice and easy to analyses function. Some information based on this document by psy_commando https://projectpokemon.org/home/docs/mystery-dungeon-nds/pmd2-pack-file-format-r42/ .
> Added information about Pack archives

- headers/functions/overlay01.h
Fix the header guard to match the file name.
> Fix header guard in overlay01.h

- .github/workflows/release.yml
- headers/functions/arm7.h
- headers/functions/arm9.h
- headers/functions/functions.h
- symbols/arm7.yml
- symbols/arm9.yml
- symbols/arm9/itcm.yml
- symbols/overlay01.yml
- symbols/overlay13.yml
- symbols/overlay29.yml
- symbols/overlay31.yml
- tools/offsets.py
Add generic info about ARM9/ARM7, including new symbol/header files for arm7.bin. Also fill in some existing symbols with JP addresses.
> Add general ARM info, JP symbols

- headers/symbol_check.py
Otherwise things in comments that match the search patterns will falsely trip the check.
> symbol_check.py: Strip comments before parsing headers

- tools/symdiff.py
- Don't rely on the error message from `git show` to detect missing files in open_file_at_revision, since these messages will differ by locale, and it's also possible that they could change.
- Explicitly parse commit range syntax for parity with `git diff`.
- Explicitly verify revisions up-front, and report a more user-friendly error message if not, as opposed to dumping a stack trace.
Fixes #95.
> Make symdiff.py more robust

- headers/functions/overlay29.h
- symbols/overlay29.yml
Added a new function and the header definition of an old function I forgot to include in overlay29.h.
> Minor changes

- headers/types/common/common.h
- symbols/arm9.yml
These two tables were mixed up.
> Swap exclusive item defense/special attack boost tables

- docs/contributing.md
For people who might otherwise want to contribute, but aren't familiar with open source contribution and don't know where to start.
> Link to GitHub contribution tutorials in contributing.md

- CREDITS.txt
- headers/functions/overlay29.h
- symbols/overlay29.yml
Added two functions that handle what should happen when an entity steps on an item.
> Added some tiny info about picking up items

- headers/functions/arm9.h
- headers/types/common/common.h
- headers/types/files/wan.h
- symbols/arm9.yml
This a structure that store the loaded Wan sprites
> Added info about the wan table

- README.md
- docs/resources.md
- Slightly restructure the top README
- Add links to AnonymousRandomPerson's DS reverse engineering tutorial as a starting resource
> Improve documentation for beginners

- check_and_format.sh
I often make mistakes that are caught by these tools. This script will run the various checks (that I’m aware of). It work on my machines, and should likely work on other unix-like OS with the required programs installed.
> Add a shell scripts that run the various checks

- headers/data/ram.h
- headers/functions/overlay11.h
- headers/types/dungeon_mode/dungeon_mode.h
- symbols/overlay11.yml
- symbols/ram.yml
From a patch I have yet to debug on NA and release.
> Added information about setting world map camera and mode

- headers/functions/overlay10.h
- headers/functions/overlay29.h
- symbols/arm9.yml
- symbols/overlay10.yml
- symbols/overlay29.yml
Adds functions mostly related to monster mobility.
A couple of existing functions have been renamed.
I started researching this area and then realized halfway through that I had already documented most of it, so I ended up accidentally dumping a new section of my notes. Oops!
> Info dump 54/66: Mobility

- headers/functions/arm9.h
- symbols/arm9.yml
I thought this was fully documented already
> Properly document GetPerformanceFlagWithChecks

- symbols/arm9.yml
Per discussion with @End45 in https://github.com/UsernameFodder/pmdsky-debug/pull/189
> Use American spelling for "initialization"

- symbols/overlay20.yml
Adds a bit more JP symbols in overlay20.
> Some ov20 JP symbols

- CREDITS.txt
- headers/functions/arm9.h
- headers/types/common/common.h
- headers/types/dungeon_mode/dungeon_mode.h
- symbols/arm9.yml
Added normal and advanced menu documentation. Mix of notes from Adex-8x's, tech-nicks, and my own findings. Also, added a few comments about the display_data struct.
> Added Menu Documentation

- headers/functions/arm7.h
- symbols/arm7.yml
This pull request completes #201 and documents GetProcessorMode.
> Document GetProcessorMode

- headers/data/ram.h
- headers/functions/arm9.h
- headers/functions/overlay29.h
- headers/functions/overlay31.h
- headers/types/common/common.h
- headers/types/dungeon_mode/enums.h
- symbols/arm9.yml
- symbols/overlay29.yml
- symbols/overlay31.yml
- symbols/ram.yml
Adds functions mostly related to:
- The game's threading system
- Map generation
- Other miscellaneous stuff that I hadn't categorized
And with this, the info dump is finally complete! Only took 1.5 years.
> Info dump 63-65/65: Threading, map generation and misc.

- symbols/arm9.yml
- symbols/overlay09.yml
- symbols/overlay10.yml
- symbols/overlay11.yml
Filling in EU addresses for new symbols in https://github.com/UsernameFodder/pmdsky-debug/pull/218.
> Added EU addresses for new window symbols

- CREDITS.txt
- headers/functions/arm9.h
- headers/types/common/common.h
- symbols/arm9.yml
Contributed by Rhokin in the SkyTemple Discord. https://discord.com/channels/710190644152369162/804247227991326730/1182773685317271634
> Added sound envelope functions

- headers/types/common/enums.h
- symbols/arm9.yml
- symbols/ram.yml
Updates the description of some debug flags and fixes their numbering. Some other findings I made in the process are also included.
> Some info about the debug flags

- headers/types/common/common.h
> Fill in more fields for struct mission

- headers/types/dungeon_mode/dungeon_mode.h
> Update enemy_density comment

- .github/actions/build-resymgen/action.yml
- .github/workflows/check-headers.yml
- .github/workflows/check-resymgen.yml
- .github/workflows/check-symbol-header-sync.yml
- .github/workflows/check-symbols.yml
- .github/workflows/release.yml
- actions/checkout@v4
- actions/upload-artifact@v4
- actions/cache@v3
> Upgrade GitHub Actions to latest versions

- symbols/arm9/libs.yml
Rhokin sent a bunch more DSE symbols. They're working on the structs and function headers, so for now this PR has just the symbol names.
> Added more DSE functions

- headers/functions/arm9.h
- headers/functions/overlay29.h
- symbols/arm9.yml
- symbols/overlay29.yml
document DisplayFloorTip and DisplayItemTip, add return for DisplayDungeonTip and specify the exact type for pack_file_id in LoadWteFromFileDirectory
> Document some dungeon tip function + fix some signature type

- headers/augment_headers.py
Adds a new flag `--mark_aliases_deprecated` to `augment_headers.py` that generates warnings such as:
```
c-of-time/src/main.c:17:3: warning: 'ProcessScriptParam' is deprecated: Renamed to 'ScriptParamToInt' [-Wdeprecated-declarations]
17 |   int x = ProcessScriptParam(123);
|   ^~~
```
I'm opening this PR as a draft because the formatter generates very weird looking code:
```c
__attribute((deprecated("Renamed to 'ScriptParamToInt'"))) int16_t
// THIS DOCSTRING WAS GENERATED AUTOMATICALLY
/**
* Converts the given opcode parameter to a signed integer.
* 
* The parameter will be returned unchanged unless one of its two most significant bits (0x8000 and 0x4000) are set, in which case both bits will be cleared and the original value will be modified according to the following two rules:
* - If …
```
> Add flag to mark aliases as deprecated to header augmentation script

- CREDITS.txt
- docs/resources.md
- symbols/arm9.yml
- symbols/overlay10.yml
> Username update

- CREDITS.txt
- headers/functions/overlay29.h
- headers/types/dungeon_mode/enums.h
- symbols/overlay29.yml
First commit. Hopefully this is acceptable?
> Some new functions related to dungeon AI behavior

- headers/data/overlay31.h
- headers/functions/arm9.h
- headers/functions/overlay29.h
- headers/types/dungeon_mode/dungeon.h
- symbols/arm9.yml
- symbols/overlay29.yml
- symbols/overlay31.yml
> Add decomp symbols

- headers/types/dungeon_mode/dungeon_mode.h
Credits to HeckaBad for pointing this out
> Fix room_data struct

- CREDITS.txt
- symbols/overlay29.yml
Courtesy of Chritchy: https://discord.com/channels/710190644152369162/712343594568253512/1310962052755488809
> Document r3 for LowerHitChanceStat

- headers/functions/arm9.h
- headers/functions/arm9/libs.h
- headers/types/common/util.h
- symbols/arm9.yml
- symbols/arm9/libs.yml
Some arm9 shenanigans involving the system clock, firmware user settings, etc.
> Small assortment of arm9 stuff

- .github/workflows/release.yml
- headers/data/ram.h
- headers/functions/arm9.h
- headers/functions/arm9/libs.h
- headers/functions/overlay29.h
- headers/functions/overlay31.h
- headers/types/common/enums.h
- headers/types/common/sound.h
- headers/types/dungeon_mode/dungeon_mode_common.h
- symbols/arm9.yml
- symbols/arm9/libs.yml
- symbols/overlay10.yml
- symbols/overlay29.yml
- symbols/overlay31.yml
- symbols/ram.yml
Not sure if the new `EntityIsValid` in overlay 31 will cause problems by conflicting with the existing one in overlay 29. It can be renamed if needed.
> Added AI symbols and audio structs

- headers/data/overlay11.h
- headers/functions/overlay11.h
- headers/types/ground_mode/ground_mode.h
- symbols/overlay11.yml
- symbols/overlay21.yml
The ground BG symbols came from @DizzyEggg from the decomp.
> Documented some ground BG functions, filled in language addresses
