- symbols/arm9.yml
- symbols/overlay11.yml
Taken from skytemple-files/pmd2data.xml. The binary lengths are
currently unknown.
> Add addresses for JP arm9/overlay11 binaries

- symbols/arm9.yml
According to SkyTemple's previous XML, this field should be 0x89 in size. Are you sure 0x8C is correct? If it is, what are the rest of the bytes for?
> Fixes IQ Skill Restriction table length

- headers/functions/arm9.h
- headers/types/common/common.h
- headers/types/common/enums.h
- symbols/arm9.yml
The end goal should be to hopefully have a fully documented API of where and how the format is used, which considering how small it is, should be rather feasible. It might be so simple in fact that it could serve as a subject for a tutorial / guide! But that's to be discussed and resolved later
> Document the WTE format and its applications

- .github/workflows/check-headers.yml
- headers/Makefile
- headers/README.md
- headers/pmdsky.h
- headers/types/common/common.h
- headers/types/common/enums.h
- headers/types/dungeon_mode/dungeon.h
- headers/types/dungeon_mode/dungeon_mode.h
- headers/types/dungeon_mode/enums.h
- headers/types/ground_mode/enums.h
- headers/types/ground_mode/ground_mode.h
- symbols/arm9.yml
- symbols/overlay10.yml
- symbols/overlay11.yml
- symbols/overlay13.yml
- symbols/overlay29.yml
- symbols/ram.yml
The `#pragma pack` directive is the only way to pack structs that
Ghidra's C parser supports, but it prevents compilers from assuming
struct alignment, which causes them to emit a lot of boilerplate code
that can be safely run even with unaligned structs. This is horribly
inefficient for writing patches using the C headers.
Most of the C structs don't actually require packing. Change structs to
be naturally aligned by default, but also keep a build target that
switches back to the old implicit packing behavior. By compiling in both
modes simultaneously, the clarity benefits of forbidding implicit struct
padding is preserved (as long as structs are accompanied by an
ASSERT_SIZE), while giving compilers more reasonable alignment
guarantees in most cases.
As part of this migration, replace …
> Don't pack structs by default

- src/formatting.rs
- src/transform.rs
- src/util.rs
On Unix systems where the temp directory is mounted on a different
filesystem from the target path (which is the case for /tmp on some
systems), NamedTempFile::persist() will fail. Fall back to fs::copy() to
handle such failures.
> Fall back to fs::copy on tempfile persist errors

- headers/functions/overlay29.h
- symbols/overlay29.yml
This parameter should be an index into the target's types, not the type
ID itself.
> Fix GetTypeMatchup's third parameter

- Cargo.toml
- docs/resymgen.md
- src/data_formats/sym.rs
- src/data_formats/symgen_yml/symgen.rs
- src/data_formats/symgen_yml/types.rs
There's no reason why resymgen shouldn't support 64-bit binaries, and as
a somewhat general-purpose tool it's arguably expected that it should.
Change Uint to u64 to allow this, and add a few tests to make sure
things still work with numbers larger-than-32-bit numbers.
Users working with 32-bit binaries should not be meaningfully affected
by this increase in maximum value, since specifying both the address and
length for each symbol block is already required, and should constrain
symbol addresses and lengths to 32-bit integers via the in-bounds
symbols check resymgen provides, even when the underlying Uint type is
u64.
> Support 64-bit integers in resymgen

- README.md
- headers/LICENSE.txt
- headers/README.md
- symbols/LICENSE.txt
- symbols/README.md
Projects like tech-ticks' c-of-time use the symbol tables and C headers
to generate actual ROM patches. However, the current GPLv3 licensing of
the symbols/headers are problematic for the distribution of these
patches, since they are inherently tied to the closed-source EoS ROMs
and thus incompatible with GPL.
Release the symbols and C headers under a dual GPLv3-MIT license to make
it easier for people to create and distribute patches derived from them.
Patch creators may choose to use the symbols and headers under the MIT
license.
Note that this commit does NOT change the license of the overall
pmdsky-debug repository, which is and remains GPLv3.
> Relicense symbols and C headers under GPLv3-MIT dual license

- Cargo.toml
- src/checks.rs
- src/data_formats/symgen_yml/bounds.rs
- src/data_formats/symgen_yml/merge.rs
- src/data_formats/symgen_yml/symgen.rs
- src/data_formats/symgen_yml/types.rs
Fixes #38.
VersionDeps map Versions to values, where a Version is an ordinal-string
pair. Within a Block, the ordinal for Version keys is determined by the
version list in the Block's metadata and makes it possible to sort
version keys according to the Block's global version list.
The problem is that intuitively, a version will often be conceptualized
as a vanilla string, without the ordinal (which is largely an
implementation detail). This leads to unexpected results when attempting
a lookup in a VersionDep or MaybeVersionDep with a Version key that
matches one of the native keys by string value, but not by ordinal (with
the end result being an unexpected return value of None). This is
especially error-prone when working with glue code between a SymGen and
foreign symbols (like with the …
> Make VersionDep value lookups more robust

- headers/types/common/enums.h
I stared at the screen for 10 minutes :clown_face:
> Fix typo in overlay_group_id_enum

- tools/arm5find.py
- tools/symbols_vfill.py
Impose that adaptive length matches must match at least 4 instructions by default in order to further limit false positives. Add an option to configure this constraint.
Testing against symbols in #47 reveals that single matches might be found even with really short lengths (3 instructions). In the case of `EuFaintCheck`, a false positive match is found in the NA version. A minimum length of 4 instructions seems like a reasonable default for adaptive lengths.
> Add minimum instruction count constraint to symbols_vfill.py

- .github/workflows/check-symbols.yml
- Cargo.toml
- docs/resymgen.md
- src/checks.rs
- src/data_formats.rs
- src/data_formats/symgen_yml.rs
- src/data_formats/symgen_yml/bounds.rs
- src/data_formats/symgen_yml/error.rs
- src/data_formats/symgen_yml/merge.rs
- src/data_formats/symgen_yml/symgen.rs
- src/data_formats/symgen_yml/symgen/cursor.rs
- src/data_formats/symgen_yml/types.rs
- src/formatting.rs
- src/main.rs
- src/transform.rs
- src/util.rs
Fixes #37. This implements the `subregions` field on blocks as proposed.
These changes are almost fully backwards compatible. The only breaking change is the renaming of one of the `resymgen check` options from `--no-function-overlap` to `--no-overlap`.
> Add subregion support to resymgen

- tools/README.md
- tools/ansi.py
- tools/resymgen.py
- tools/symbols_vfill.py
- tools/symdiff.py
Resolves #58.
It can be useful to know what symbols have changed with each
commit/revision, or across a sequence of commits.
It's possible to determine this by viewing the Git history or using
`git diff`, but these don't make for very clean symbol changelogs. It's
also possible to diff different symbol packages generated by resymgen,
but the process is still quite cumbersome, and the resulting changelog
misses some useful information (like where the modified symbols are in
the original symbol tables).
The new `symdiff.py` script runs a specialized diffing algorithm to
automatically generate a high-quality symbol changelog between different
Git revisions.
> Add symbol table diffing tool

- docs/using-debug-info.md
Each ROM version now has multiple subfolders from which symbols must be copied, so I figured it would be good to include this information in the instructions on how to properly load .sym files into No$GBA.
> Update instructions to use .sym files on No$GBA

- headers/types/common/common.h
- headers/types/ground_mode/ground_mode.h
While I still have some willpower remaining today (and it's 8AM...)
> added basic live actors data

- headers/functions/overlay29.h
- headers/types/dungeon_mode/dungeon.h
- headers/types/dungeon_mode/dungeon_mode.h
- symbols/overlay29.yml
Added some information on status effect icons.
I think the `f_red_exclamation_mark` bit is unused, if you know of a status effect that actually uses it let me know.
> Status icons

- headers/Makefile
- headers/symbol_check.py
- Add an --extra-symbols flag to print out symbols that exist in the symbol tables but not the C headers, and an associated symbol-check-extra target in the Makefile.
- Add a --verbose flag for verbose output.
- Slightly improve output to specify the symbol type (functions/data)
> Improve symbol_check.py

- docs/ghidra-setup.md
Ghidra 10.2's ARM disassembler is currently broken, so add a note about this in the Ghidra setup guide.
> Add note to ghidra-setup.md about Ghidra 10.2

- headers/data/overlay11.h
- headers/functions/overlay11.h
- headers/types/ground_mode/ground_mode.h
- symbols/overlay11.yml
This is the main ground mode overlay. Essentially a straight port, plus some verification of a few of the symbols by me.
Note: The data symbol now labeled as OVERLAY11_UNKNOWN_TABLE__NA_2316A38 was listed in Irdkwia's notes as having 20 (typo'd as 2) 8-byte entries, but from investigation, it seems like they're actually 4-byte entries. The type is now listed as undefined4[40].
> Port overlay_0011 from Irdkwia's ASM.ods

- tools/symdiff.py
Apparently there's an error message from `git show` for when a path exists on disk, but not in the specified revision. This is conceptually the same as the path not existing, so it should likewise be treated as a FileNotFoundError.
> Catch another FileNotFoundError in symdiff.py

- headers/data/overlay10.h
- headers/functions/functions.h
- headers/functions/overlay10.h
- headers/types/dungeon_mode/dungeon_mode.h
- symbols/overlay10.yml
This is the shared mechanics info overlay in dungeon/ground mode, although most of the info is relevant to dungeon mode. Rename some of the functions, do more investigation into struct formats for various data tables, and make miscellaneous corrections.
Parent issue: #81
> Port overlay_0010 from Irdkwia's ASM.ods

- docs/ghidra-setup.md
The ARMv5 disassembler bug from 10.2 was fixed in 10.2.1 (GP-2812). Add a note to the Ghidra setup doc about this.
Closes #86.
> Update ghidra-setup.md with note on Ghidra 10.2.1.

- headers/data/overlay29.h
- headers/functions/overlay29.h
- headers/types/dungeon_mode/dungeon_mode.h
- symbols/overlay29.yml
The dungeon mode overlay. Ported stuff from the spreadsheet with assorted tweaks:
- Corrected some mistakes
- Did further investigation
- Renamed various symbols to match style conventions
- Consolidated various addresses into existing symbols
This is the last remaining overlay. The only thing left is ARM9.
Parent issue: #81
> Port overlay_0029 from Irdkwia's ASM.ods

- symbols/arm9.yml
- symbols/arm9/itcm.yml
pmdsky-debug-py couldn't handle the lack of block-level metadata in this file after JP offsets were added to some of the functions. Add that metadata in.
Interestingly, the length of the JP ITCM region is slightly different from that of the EU/NA ITCM region.
> Add JP/JP-ITCM metadata to arm9/itcm.yml

- Cargo.toml
- src/checks.rs
- src/data_formats/symgen_yml/types.rs
- src/formatting.rs
- src/transform.rs
Improve the usability of `resymgen gen` with unversioned addresses. Also add some warning messages in places where unexpected behavior could occur.
> Minor usability tweaks for resymgen

- docs/ghidra-setup.md
- docs/using-debug-info.md
The steps describing symbol imports don't make it very obvious that you shouldn't blanket-load every single overlay file at once. Rearrange things and add warnings to make this slightly more difficult to miss.
> Reword some documentation to be clearer

- .github/workflows/release.yml
The set-output command is being deprecated in favor of the newer $GITHUB_OUTPUT environment file, so switch over to using that in release.yml.
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> Use GITHUB_OUTPUT env file for release actions

- headers/data/overlay10.h
- headers/data/overlay29.h
- headers/functions/overlay29.h
- headers/types/dungeon_mode/dungeon_mode.h
- headers/types/dungeon_mode/enums.h
- symbols/overlay10.yml
- symbols/overlay29.yml
- symbols/overlay29/move_effects.yml
Adds some symbols related to moves, move effects and item effects.
I also added the EU offset of some `DoMove___` functions I stumbled upon, but there's still a lot of EU offsets missing for those.
> Info dump 28/66: Moves and effects

- headers/functions/arm9.h
- headers/types/dungeon_mode/dungeon_mode.h
- symbols/arm9.yml
Adds details for one of the previously unknown dungeon restrictions. Thanks to @AnonymousRandomPerson for pointing out the fact that this field is the same as a flag used in RRT and providing an explanation on how it works.
> Document random movement chance

- headers/functions/arm9.h
- headers/types/dungeon_mode/dungeon_mode.h
Just checked the ASM again, it's actually a signed 2-byte value.
> Fix size of the random movement chance restriction

- headers/types/common/common.h
- headers/types/dungeon_mode/dungeon.h
- headers/types/dungeon_mode/dungeon_mode.h
- headers/types/dungeon_mode/dungeon_mode_common.h
- headers/types/dungeon_mode/enums.h
Added more information about statuses that have to track another target and how the game handles generating dungeons from other versions of the game.
In case someone wanted to review the changes for dungeon::0x7CC, I have listed a few addresses (NA) that can be reviewed.
HiddenStairs fail - 0x02342DB0
MappaFileLoading - 0x022E705C
Poke/Money - 0x0234734C
ExclusiveItem - 0x023462E4/0x02346298
Waza_P2 - 0x022FBF3C/0x022FBF14
> Added more statuses and dungeon version loading info

- headers/types/common/enums.h
- headers/types/ground_mode/enums.h
- headers/types/ground_mode/version_dep_enums.h
Mostly a verbatim port, with minor tweaks and additions.
There's some obvious follow-up research that can be done here:
- Investigating the raw function/data offsets mentioned in the comments and adding actual symbols for them
- Locating data symbols that back some of the special script variables whose values don't come from the script var value table, and/or investigating the relationship between these script variables and existing  data symbols.
- Tracing special process code to glean more information about related script variables
- Tracing known ARM9 functions that definitely or likely coincide with script variables, such as `Load/SaveScriptVariableValue`, `GetPerformanceFlagWithChecks`, etc.
> Port Adex's script_variable_meanings.txt

- headers/functions/overlay29.h
- headers/types/dungeon_mode/dungeon_mode.h
- headers/types/dungeon_mode/enums.h
- symbols/arm9.yml
- symbols/overlay29.yml
Adds functions mostly related to:
- Determining when or how to display monsters
- Player input and automated player actions
I also updated `OpenMenu`. I don't know why it had a fourth parameter listed, that doesn't seem to be the case.
> Info dump 32-34/66: Invisibility and player input

- headers/functions/arm9.h
- headers/functions/functions.h
- headers/functions/overlay11.h
- headers/functions/overlay29.h
- headers/functions/overlay30.h
- headers/types/common/enums.h
- headers/types/dungeon_mode/dungeon.h
- headers/types/dungeon_mode/dungeon_mode.h
- headers/types/dungeon_mode/enums.h
- symbols/arm9.yml
- symbols/overlay11.yml
- symbols/overlay29.yml
- symbols/overlay30.yml
Adds functions mostly related to:
- Exclusive items
- Quicksaving
- The grid that shows up in dungeon mode when you hold Y
- Moving pokémon to a different position
- Dungeon tiles
- Dungeon results screen ("The Last Outing")
- Fixed rooms
- Includes some functions about spawning and initializing entities, since I documented those when I started researching fixed rooms
`InitMonster` has been renamed to `SubInitMonster`, since there's another function above it that is the main function responsible for initializing a new monster.
> Info dump 36-43/66: Many things

- Cargo.toml
- src/checks.rs
- src/main.rs
Allow the `--function-names` and `--data-names` options for `resymgen check` to be specified more than once with different values, which will check that at least one of the specified naming conventions is satisfied.
Closes https://github.com/UsernameFodder/pmdsky-debug/issues/152.
> resymgen: Support multiple naming conventions in checks

- symbols/README.md
Locally run checks need to permit snake_case function names, like the automated tests do.
> Update dev test instructions in symbols README

- headers/functions/overlay11.h
- headers/functions/overlay29.h
- headers/types/common/common.h
- headers/types/common/enums.h
- symbols/overlay11.yml
- symbols/overlay29.yml
I’m still a bit unsure in which order I want to add stuff in pmdsky-debug. I think I’ll for now focus in the palette in overlay11 stuff. But I did that in the meantime.
Also, I think portrait_box is the "kaomodo" struct in this PR: https://github.com/UsernameFodder/pmdsky-debug/pull/21/files
> Info regarding portrait box, live actor direction and music in dungeon

- headers/functions/arm9.h
- headers/functions/overlay10.h
- symbols/arm9.yml
- symbols/overlay10.yml
- symbols/overlay29.yml
Renames `CheckEndDungeon` to `MainGame` and documents it in more detail.
> Properly document MainGame

- headers/data/overlay11.h
- headers/data/ram.h
- headers/functions/arm9.h
- headers/types/common/common.h
- symbols/arm9.yml
- symbols/overlay11.yml
- symbols/ram.yml
- Document the locations of all 4 known memory arenas
- Add a couple more sound-engine-related functions (mostly taken from the Project Pokémon docs).
- Move `WORLD_MAP_MODE` into overlay11.
> Memory mapping + miscellaneous sound functions

- headers/data/arm9.h
- headers/data/arm9/itcm.h
- headers/functions/arm9.h
- headers/functions/arm9/itcm.h
- headers/functions/overlay29.h
- headers/types/common/graphics.h
- headers/types/files/wan.h
- symbols/arm9.yml
- symbols/arm9/itcm.yml
- symbols/overlay29.yml
I had this lying around since about 2 weeks, but finally decided to do the needed finalisation.
The gist of that is the game use the 3D rendering system to render a few things. From what I’ve seen, it mostly include weather and text box border/background, but could be easily extended (and is what Irdkwia used for the moving spirit effect in the "angry" part of Tangent’s hack (that I can’t remember the name of).
> Some 3d engine documentation

- headers/types/ground_mode/enums.h
- symbols/arm9.yml
Based on the implementing function names, it seems like we already know what these special processes are, so rename the enum values.
> Rename some special process IDs

- headers/types/common/util.h
The green and blue bytes were presumably swapped accidentally.
> Fix struct rgba field ordering

- symbols/literals.yml
- symbols/overlay18.yml
- symbols/overlay19.yml
- symbols/overlay20.yml
- symbols/overlay21.yml
- symbols/overlay22.yml
- symbols/overlay23.yml
- symbols/overlay24.yml
- symbols/overlay25.yml
- symbols/overlay27.yml
- symbols/overlay29.yml
- symbols/overlay31.yml
- symbols/overlay34.yml
Adds various JP symbols in some overlays (ranging from 18 to 34). Related to https://github.com/SkyTemple/skytemple-files/issues/235.
> Various JP symbols (ov18 - ov34)

- symbols/arm9.yml
- symbols/arm9/itcm.yml
- symbols/overlay10.yml
- symbols/overlay11.yml
- symbols/overlay29.yml
- symbols/overlay30.yml
- tools/offsets.py
- tools/symbols_vfill.py
- Check symbol order in `symbols_vfill.py` by default to reduce false positives
- Add ITCM support to `offsets.py` and `symbols_vfill.py`
- Fill in 491 function addresses for unknown versions found by `symbols_vfill.py`
- Miscellaneous bug fixes
> Upgrade symbol-address-inference tools + auto-fill function addresses

- symbols/arm9.yml
- symbols/literals.yml
- symbols/overlay11.yml
- symbols/overlay14.yml
- symbols/overlay15.yml
- symbols/overlay16.yml
- symbols/overlay17.yml
- symbols/ram.yml
Adds various JP symbols in arm9, ram, and some overlays (ranging from 00 to 17; commit name is wrong, oops). Related to https://github.com/SkyTemple/skytemple-files/issues/235.
> Various JP symbols (arm9, ram, ov00 - ov17)

- symbols/overlay01.yml
_Oops, forgot to add this in my earlier commit_
Adds some overlay01 JP symbols and should close https://github.com/SkyTemple/skytemple-files/issues/235.
> A bit of overlay01 JP symbols

- symbols/overlay29.yml
Updated the JP symbol for FIXED_ROOM_ENTITY_SPAWN_TABLE to its proper address. Should hopefully fix https://github.com/SkyTemple/skytemple/issues/602?
> Corrected JP symbol for FIXED_ROOM_ENTITY_SPAWN_TABLE

- symbols/overlay11.yml
This fixes LEVEL_TILEMAP_LIST having no block length defined for JP. Note: I didn't actually check the block length.
Closes https://github.com/SkyTemple/skytemple-files/issues/411
> Fix LEVEL_TILEMAP_LIST having no JP block length

- headers/types/common/enums.h
Credit to @Laioxy, see:
https://github.com/SkyTemple/skytemple-files/issues/410
(Note that this is unrelated to the SkyTemple issue, other than using the information provided within it)
> Rename ABILITY_UNNAMED_0x74 to ABILITY_MULTITYPE

- .gitignore
- headers/functions/arm9.h
- headers/functions/overlay11.h
- headers/functions/overlay29.h
- symbols/arm9.yml
- symbols/overlay11.yml
- symbols/overlay29.yml
- Core functions that are standard across most DS/NitroSDK games (e.g., crt0 init functions).
- Veneers auto-detected by Ghidra while setting up the decomp.
> Synced function symbols from decomp

- symbols/ram.yml
Add the address of the symbols you discovered while researching about team members in the JP version.
> Added TEAM_MEMBER_TABLE for JP version

- .github/workflows/check-headers.yml
- headers/Makefile
Since introducing versioned headers, the header make targets were compiling the base pmdsky.h at the same time as the versioned variants. This means that if a version-agnostic error is introduced, building a make target would essentially print the same error 4 times, one for each header variant. This is annoying, especially since the vast majority of errors aren't going to be version-specific.
Now, compile the base pmdsky.h first, and only move onto the versioned headers if pmdsky.h is valid. This way, most errors will only be printed once.
Also suppress -Wincompatible-library-redeclaration in the automated workflows (caused by redefined builtins); these are unnecessarily noisy and aren't useful.
> Improve dev experience around header compiler errors

- symbols/arm9.yml
Double-checked `CART_REMOVED_IMG_DATA`'s size in the NA ROM; it should be the same size as its EU and JP counterparts.
> Correct CART_REMOVED_IMG_DATA NA size

- CREDITS.txt
- headers/functions/arm7.h
- symbols/arm7.yml
I was working on some arm7 reversing and found some mirrored code between arm9 and arm7 where `EnableIrqFlag` and `SetIrqFlag` were being used, and from there I was able to find a few more arm9 interrupt functions in the arm7 as well. Interestingly although all of these ones are identical, the last interrupt function `GetIrqFlag` is not, and it does an `and` with a different mask, so I didn't include it here.
Also a note for all future arm7 documentation: I did a checksum on the `arm7.bin` of all three editions of EoS and they are all identical (`SHA256 CB2A9B26D77A6E7D0ADD85C27E3642105918695D040D02F70D5EBC1D52C9495B`), and since they are also all loaded at `0x2380000`, addresses for all editions will be identical if the function is in the binary. There do appear to be some functions that …
> Some arm7 interrupt documentation

- headers/data/overlay11.h
- headers/data/ram.h
- headers/functions/arm9.h
- headers/functions/overlay11.h
- headers/types/common/common.h
- headers/types/ground_mode/enums.h
- headers/types/ground_mode/ground_mode.h
- symbols/arm9.yml
- symbols/overlay11.yml
- symbols/ram.yml
Adds functions mostly related to how overlays are loaded and scripting/ground mode code.
I don't know what to do with the size check for `struct animation_data`. I defined the struct to better specify how the different bits in the value (which is just a halfword) work, but that pushes its size to 4 bytes due to padding.
> Info dump 56-57/66: Overlay loading and scripting

- headers/functions/arm7.h
- symbols/arm7.yml
- symbols/arm9.yml
Note: I'd appreciate advice on how I should structure this! I've looked at how the ITCM documentation is done which I guess would be the closest parallel to this but how the addresses are documented I don't quite understand.
Changed the arm7 addresses to reflect addresses after the memory map inside of the entry function as these addresses are the ones used by function calls and accessing constants.
I'm not quite sure what to name these areas, but for now I have them named as ENTRY, WRAM, and SLOW.
ENTRY is the very small chunk of code used solely for mapping the memory.
WRAM is where a lot of important functions like the irq functions, the stdlib math functions, and the arm7 main event loop reside. (Interestingly the copy seems to copy partially into the Shared WRAM instead of just into …
> Further Arm7 documentation, as well as a note on FileRead limitations

- symbols/arm9.yml
- symbols/overlay10.yml
- symbols/overlay11.yml
- symbols/overlay29.yml
- symbols/overlay30.yml
While syncing NA and EU with the decomp, I ran into a number of incorrect addresses that conflicted between versions. I manually resolved each of these, attempting to favor the version that the original contributor used.
> Fixed some incorrect addresses

- symbols/arm9.yml
- symbols/overlay10.yml
The following symbol addresses conflicted for JP. I inferred the fixed addresses based on the relative addresses of US/EU.
- `MIN_IQ_EXCLUSIVE_MOVE_USER` and `MIN_IQ_ITEM_MASTER` 
- `FACADE_DAMAGE_MULTIPLIER` and `IMPRISON_TURN_RANGE`
> Fixed duplicate JP addresses

- .github/workflows/check-symbols.yml
- check_and_format.sh
- src/checks.rs
- src/data_formats/symgen_yml/merge.rs
- src/main.rs
- symbols/README.md
Some other sources use symbol names with hybrid naming conventions. Add support for a few more sensible conventions in `resymgen`, and loosen the restrictions for pmdsky-debug function names to include `Pascal_Snake_Case` (multiple underscore-delimited `PascalCase` parts).
Support for the following new naming conventions has been added to `resymgen` for general use:
- `camel_Snake_Case` (`camelCase_Then_PascalCase`)
- `underscoreSeparated_camelCase`
- `Pascal_Snake_Case` (`UnderscoreSeparated_PascalCase`)
- `flatcase`
- `UPPERFLATCASE`
> Support more naming conventions for symbol names

- headers/functions/arm9.h
- headers/types/common/window.h
- headers/types/dungeon_mode/enums.h
- symbols/arm9.yml
- The function to update window contents was missing, even though it was referenced in a comment
- Added unknowns to `enum fade_status_dungeon`
- Added two bits to `struct preprocessor_flags`. Current only known purpose is that it's used when creating the play time string.
> Miscellaneous missed stuff from the last PR

- headers/functions/arm9.h
- symbols/arm9.yml
This is more consistent with functions from decompilation projects.
> Rename some functions to use Pascal_SnakeCase

- headers/add_header_docstrings.py
Ensures that these lines are excluded in some IDEs and doc generation tools.
> Make docstring preamble a regular comment instead of a doc comment

- headers/functions/arm9/libs.h
- symbols/arm9/libs.yml
Rhokin originally named the DSE sound library functions with Pascal_SnakeCase, but I had to change them because the format wasn't supported at the time. Now that the format is supported, renaming the functions to match their original intention.
> Used original Pascal_SnakeCase for sound functions

- .github/workflows/release.yml
- symbols/arm7.yml
- symbols/arm9.yml
- symbols/arm9/libs.yml
- tools/symcompat.py
Alias symbols with name changes in https://github.com/UsernameFodder/pmdsky-debug/pull/230 and https://github.com/UsernameFodder/pmdsky-debug/pull/236. Also collapse the weird `EXCLUSIVE_ITEM_ATTACK_BOOSTS` symbol into an alias.
Also includes miscellaneous fixes to `symcompat.py` and to `DebugDisplay` and `DebugPrint0`.
> Add aliases for relevant old symbol names

- headers/functions/arm9.h
The defined function types are already pointers, so they should be used directly instead of adding another level of pointers.
> Fix function pointer args for menu functions

- headers/functions/overlay29.h
- symbols/overlay29.yml
Better documents `GetSleepAnimationId`, which is actually used to get the animation a monster should play while idling. The function has been renamed to `GetIdleAnimationId`.
Also documents `ChangeMonsterAnimation`.
> Replace GetSleepAnimationId with GetIdleAnimationId

- headers/functions/overlay29.h
- symbols/overlay29.yml
`ExecuteMonsterAction` is supposed to have a return value, which became apparent after trying to hook calls to this function via a wrapper with a `void` return type and watching every Pokémon attack three times in a row. The actual return value seems to be a `bool` because either 0 or 1 are moved into r0 before the function returns.
> Fix `ExecuteMonsterAction` return value

- symbols/arm9.yml
- symbols/arm9/libs.yml
- symbols/overlay01.yml
- symbols/overlay09.yml
- symbols/overlay10.yml
- symbols/overlay11.yml
- symbols/overlay13.yml
- symbols/overlay14.yml
- symbols/overlay15.yml
- symbols/overlay16.yml
- symbols/overlay17.yml
- symbols/overlay18.yml
- symbols/overlay19.yml
- symbols/overlay20.yml
- symbols/overlay21.yml
- symbols/overlay22.yml
- symbols/overlay23.yml
- symbols/overlay24.yml
- symbols/overlay25.yml
- symbols/overlay27.yml
- symbols/overlay29.yml
- symbols/overlay29/move_effects.yml
- symbols/overlay30.yml
- symbols/overlay31.yml
- symbols/overlay34.yml
- symbols/ram.yml
The decomp now produces a matching JP build, which allows determining all JP symbol addresses in the ROM.
> Add all non-RAM JP addresses

- headers/functions/arm9.h
- symbols/arm9.yml
Renames `GetLowKickMultiplier` to `GetWeightMultiplier` so it's a bit more consistent with the name that is usually given to this field in monster data ("weight").
I had no idea this value was a fixed-point number. Everyone has been treating it as an integer so far.
> Clarify monster weight value

- headers/data/literals.h
- headers/data/overlay29.h
- symbols/literals.yml
- symbols/overlay29.yml
Adds two symbols related to dungeon sprite buffer size, which controls how many bytes are used in the main heap to store sprite file data in dungeon mode.
> Add dungeon sprite buffer size

- symbols/overlay29.yml
Only the EU addresses were correct. The NA/JP addresses were incorrectly derived by copying the offset differences between versions of other unrelated symbols.
The correct symbols were found by symbols_vfill.py
> Fix NA/JP addresses from #266

- symbols/overlay29.yml
Used the decomp to fill some addresses missed by `symbols_vfill.py` for new symbol additions.
`SetDecoyAiTracker` doesn't exist in JP, so that will remain with only EU/US addresses.
> Fill some language symbol addresses

- headers/functions/overlay29.h
- symbols/arm9.yml
- symbols/overlay29.yml
New functions were labeled in the decomp by chordtoll.
Also filled in region addresses for the new badge/rank symbols.
> Sync entity pixel pos funcs from decomp

- headers/functions/arm9.h
- headers/functions/overlay29.h
- headers/types/common/common.h
- headers/types/dungeon_mode/dungeon.h
- headers/types/dungeon_mode/dungeon_mode.h
- headers/types/dungeon_mode/dungeon_mode_common.h
- symbols/arm9.yml
- symbols/overlay29.yml
- symbols/ram.yml
Add GendersOppositeNotGenderless and TryRemoveTrap. Minor dungeon notes, adding power point boost flags to  moves struct, and adding hidden power to struct team_member.
> Minor Dungeon Notes & Trap Function

- symbols/overlay29.yml
Change the few places that use "returns:" to use the standard "return:" instead.
> Standardize wording for return values

- headers/functions/arm9.h
- headers/functions/overlay11.h
- symbols/arm9.yml
- symbols/overlay11.yml
Adds a few functions that were [only documented in CoT](https://github.com/SkyTemple/c-of-time/blob/8a1af65e4fc8d672ce458e690ab42b88c738403b/src/menus.c#L9-L13), mainly to then follow up by editing CoT to rely on the pmdsky-debug names.
~~`ScriptCaseProcess` isn't yet in CoT, but I was planning on using it for adding more custom ground instruction support, so why not get it out of the way now~~
> Add a few functions previously documented only in CoT

- symbols/overlay11.yml
These addresses are in the middle of their respective tables. Fixing these to be at the beginning of the tables.
> Fix ov11 function table addresses for EU

- .github/workflows/release.yml
- headers/pmdsky.h
The char type is special in that the C spec allows it to be either signed or unsigned depending on the target platform. Explicitly use signed char to defined int8_t instead, for portability.
See https://www.open-std.org/JTC1/SC22/WG14/www/docs/n1256.pdf, section 6.2.5/15
> Use signed char for int8_t

- headers/types/common/graphics.h
- headers/types/files/wan.h
- headers/types/ground_mode/ground_mode.h
Some small fix and improvement for what I’m working on.
Note that I’m still not 100% sure of how to properly handle offset_x, but it work in my implementation.
> Fix anim_ctrl embed in animation + wan fragment + some animation_control fields

- CREDITS.txt
- headers/functions/overlay29.h
- symbols/overlay29.yml
Was listed as an entity pointer; should be a monster pointer.
> Corrected input of GetMonsterDisplayNameType

- headers/data/arm9.h
- headers/types/common/common.h
- headers/types/common/enums.h
- headers/types/dungeon_mode/enums.h
For the most part, this was just a port of psy_commando's existing documentation: https://projectpokemon.org/docs/mystery-dungeon-nds/monstermd-file-format-r56/
> Documented the monster data table (monster.md)
